### ISSUE TITLE
All categories were classified into the same category

### ISSUE THREAD

**Issue by SH-Diao123** [mahmoodlab/HIPT#19]
I was using a tcga dataset for grading learning. However,  the results showed that all categories were classified into the same category in stage 3, i.e.,  final fine-tune WSI stage. The training losses  had converged in stages 256 and 4096.

Have you ever met such this problem, and  how did you solve it？
If not， could you tell me what can I do next step?

Thanks!

**Comment by Richarizardd** [comment]
Hi @SH-Diao123
1. What do you mean by the "training losses had converged in stages 256 and 4096?"
2. What kind of model were you using for slide-level tissue grading, and how are the different ViTs initialized + finetuned?
3. What kind of grading problem are you working on? Depending on the # of samples and the problem, there may not be enough samples to solve your downstream task well.

Haven't met such a problem (and may be beyond the scope of this GitHub issue), but for your grading problem, I would recommend starting with simple baselines first (e.g. - ABMIL), thinking about the key inductive biases / histopathologic features that are used by human pathologists in grading. A grading task that may not benefited by HIPT isFuhrman Grading in CCRCC (now outdated), which uses nuclear size + shape instead of context for grading.
