### ISSUE TITLE
Training procedure for custom dataset?

### ISSUE THREAD

**Issue by smartdanny** [mahmoodlab/HIPT#21]
Hi great work and repo :)

I wanted to try this on a private dataset of WSIs at my lab. Do you have instructions for doing this? Cant find a clear path. Seems like the 3 stages must be trained independently?

**Comment by Richarizardd** [comment]
Hi @smartdanny - Pointing you to #25 on getting started for weakly-supervised learning. One can use the [CLAM](https://github.com/mahmoodlab/CLAM) package via adjusting the patch size to be ```4096 x 4096``` @ 20X (make sure to account for discrepancies between level 0 and 1 for some WSIs). After that, you can use [HIPT_4K](https://github.com/mahmoodlab/HIPT/tree/master/HIPT_4K) for direct feature extraction from the WSI (using the coordinates `h5` files generated via CLAM). HIPT_4K would save both: 1) pre-extracted ```256 x 256``` features (from non-overlapping in ```4096 x 4096``` windows), e.g. ```[M x 256 x 384]```-shape tensor for ```M``` 4K regions, with 256 ```256 x 256``` patches per 4K region and 384=embed_dim, and 2) pre-extracted ```4096 x 4096``` features, e.g.  e.g. ```[M x 192]```-shape tensor where 192==embed_dim.

For hierarchical pretraining instructions, you can see [this folder](https://github.com/mahmoodlab/HIPT/tree/master/1-Hierarchical-Pretraining), in which pretraining does need to be performed in stages. First, a ViT model (for ```256 x 256``` images with token size ```16 x 16```) is pretrained via [DINO](https://github.com/facebookresearch/dino) (most of the code is as-is). Then, a 2nd ViT model (for ```4096 x 4096``` images with token size ```256 x 256```) is pretrained also via DINO. The trick is, is that: 1) the tokens for ```4096 x 4096``` are pre-extracted so your inputs for pretraining is a ```1 x 16 x 16 x 384```-shape tensor for each image, where the ```16 x 16``` dimensions are the number of tokens along the width and height after patchifying, 2) the complexity for pretraining the 2nd ViT is the same as pretraining the 1st ViT. 

The main adaptations going from 256- to 4096-resolution is as such:
- [DataLoader](https://github.com/mahmoodlab/HIPT/blob/b5f4844f2d8b013d06807375166817eeb939a5aa/1-Hierarchical-Pretraining/main_dino4k.py#L426): Instead of folder of images, we are working with a folder of patch embeddings.
- [Augmentations](https://github.com/mahmoodlab/HIPT/blob/b5f4844f2d8b013d06807375166817eeb939a5aa/1-Hierarchical-Pretraining/main_dino4k.py#L441): Instead of ```224 x 224 / 96 x 96``` global / local crops as in DINO, we are performing ```14 x 14 / 6 x 6``` crops in the 2D grid of pre-extracted feature embeddings.

Let me know if this comment was helpful!

**Comment by GzrDavidRicardo** [comment]
Hi there. Thanks for this great work. May I ask if there is a tutorial for using HIPT_4K to conduct feature extraction for 4096 x 4096 patches?
