### ISSUE TITLE
tar_patch_4096 with webdataset API

### ISSUE THREAD

**Issue by JuanDuranMcgill** [mahmoodlab/HIPT#38]
Hello, 
Thank you for your great work. 

I am trying to recreate the folder structure for weakly supervised learning. 

I am trying to create the tar_patch_4096 folder. 

The description is:

Directory of saved [4096 × 4096] image regions for each WSI, stored in a *.tar format using [WebDataset](https://github.com/webdataset/webdataset) API.

I am not sure how to proceed here, Do I take the .h5 patches and turn them into .tar files? 

Thank you, 

Juan

**Comment by JuanDuranMcgill** [comment]
For example, do I take the directories from each patch, turn them into json files, and then store them with "from webdataset import TarWriter"? I am trying to figure out how the information is stored.

**Comment by Richarizardd** [comment]
Hi @JuanDuranMcgill 

You do not need to turn the images into a *.tar format for WebDataset. Originally, all 400K-ish [4096 × 4096] images were saved in a WebDataset format, to prevent reading directly from Openslide. However, like CLAM, its much easier to just extract features directly from the WSI rather than to 1) save the image patch, then 2) extract features.

How are you extracting features? I would modify the CLAM feature extraction pipeline to directly use HIPT_4K for feature extraction of specified 4096 x 4096 patches.
