### ISSUE TITLE
Some issue about create patch.

### ISSUE THREAD

**Issue by icherishxixi** [mahmoodlab/HIPT#51]
Thanks for your intuitive work for Wsi classification. Could you please inform me some details about the feature extraction. Here are some questions of me to process tagc_lung.
1. To extract features in 256*256 patches for MIL baseline, we set patch_size=256 in [create_patches.py](https://github.com/mahmoodlab/CLAM/blob/master/create_patches.py) of CLAM to generate patch (python create_patches_fp.py --source DATA_DIRECTORY --save_dir RESULTS_DIRECTORY --patch_size 256 --preset bwh_biopsy.csv --seg --patch --stitch). Subsequently, [model is changed to pre-trained ViT16](https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/extract_features_fp.py#L88)  in extract_features_fp.py of CLAM to extract features. Is it correct?
2. To extract features in 4096*4096 patches for HIPT baseline, we set patch_size=4096 in create_patches.pyof CLAM. Then model is changed to [hipt_4k ](https://github.com/mahmoodlab/HIPT/blob/b5f4844f2d8b013d06807375166817eeb939a5aa/HIPT_4K/hipt_4k.py#L31)in extract_features_fp.py of CLAM to extract features (pre-trained ViT16 and ViT4k are both utilized in hipt_4k model).  Is it correct?
3. If instruction 2 is correct. I wonder how to fast extract features with hipt_4k because its [default batch_size is set to 1](https://github.com/mahmoodlab/HIPT/blob/b5f4844f2d8b013d06807375166817eeb939a5aa/HIPT_4K/hipt_4k.py#L63). Did you change the hipt_4k for a bigger batch size or take several servers to extract features. (If I process almost 900 slides on two Nvidia 3090 with batch_size = 1, almost 80 days will be consumed.)

**Comment by Richarizardd** [comment]
HI @icherishxixi 
- Instruction 2 is correct. When extracting features from 4K images, I set the batch size to be 1. The batch size is much smaller than that of extracting features for 256 images, but the # of images to also extract features from is geometrically smaller as well. On average, there are ~30-40 4K images in WSI resections in TCGA. The speed for feature extraction thus ends up being approximately the same (at the end of the day, you are extracting features from a "batch of 256-sized images", as the 4K image is unraveled into a sequence of 256-sized images).
- For feature extraction, I typically set up only one `extract_features_fp.py` script per GPU (no `nn.DataParallel`). Depending on the # of workers on your machine, I also set the number of threads accordingly. Hypothetically, let's say your workstation has 2x3090 GPUs and 20 threads. For a folder of 1K WSIs, I would divide up my `process_list_autogen.csv` into two partitions, and then launch two separate `extract_features_fp.py` scripts with `CUDA_VISIBLE_DEVICES=0` and `CUDA_VISIBLE_DEVICES=1`, with `num_workers=8`. I found also setting the number of works to be crucial in speeding up feature extraction speed (much better speed than 4, but little gains with 16).

**Comment by Rainydu184** [comment]
so we just need to get the patch in 4096,  then using the hipt_4k model to extracting feature by extract_features_fp.py?

**Comment by pniedziela** [comment]
That's how I understood it and I'm doing now. You will have to change this part too if you follow extraction on a single GPU: 
`device4k=torch.device('cuda:0')):  # IT WAS CUDA 1 ORIGINALLY`

**Comment by Rainydu184** [comment]
@pniedziela  I have completed the procedure for this experiment. By the way, you need to get the feature[N, 256, 384], not the[N, 192]

**Comment by pniedziela** [comment]
So you mean to proceed with the **features_cls256** (before reshaping) instead of **features_cls4k** (in the hipt_4k.py)? 
You just saved me from having a lot of trouble 👍

**Comment by Rainydu184** [comment]
yes. And you need to return the feature_cls256 by add "features_cls256 = features_cls256.unsqueeze(0)" before the function of return. If you dont add it, you will get feature [N*256, 384].
&nbsp;


木土木目龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Przemysław ***@***.***&gt;; 
发送时间: 2023年7月3日(星期一) 晚上8:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mahmoodlab/HIPT] Some issue about create patch. (Issue #51)





 
So you mean to proceed with the features_cls256 (before reshaping) instead of features_cls4k (in the hipt_4k.py)?
 You just saved me from having a lot of trouble 👍

**Comment by pniedziela** [comment]
Great, thank you! I would waste a lot time with [N, 192] otherwise.

**Comment by Rainydu184** [comment]
@pniedziela  Could you let me know your email? I think we can have more discussions about this research direction.

**Comment by ShiCrazy** [comment]
> @pniedziela Could you let me know your email? I think we can have more discussions about this research direction.

Could you tell me how you modified your extract_patches_fp.py? I would really appreciate it if you could give me some specific instructions. My email address is [shigb@origimed.com](mailto:shigb@origimed.com) (company email) or [602192794@qq.com](mailto:602192794@qq.com) (private email).

**Comment by pniedziela** [comment]
@ShiCrazy you have to edit "hipt_4k.py" starting from line 77: 
```
features_cls256 = torch.vstack(features_cls256)  # 3. [B x 384], where 384 == dim of ViT-256 [ClS] token.

# features_cls256 = features_cls256.reshape(w_256, h_256, 384).transpose(0,1).transpose(0,2).unsqueeze(dim=0)
# features_cls256 = features_cls256.to(self.device4k, non_blocking=True)  # 4. [1 x 384 x w_256 x h_256]

features_cls256 = features_cls256.unsqueeze(0)
# features_cls4k = self.model4k.forward(features_cls256)                  # 5. [1 x 192], where 192 == dim of ViT-4K [ClS] token.
return features_cls256`
```
Plus in line 44 change cuda device to "0":
`device4k=torch.device('cuda:0')):`

Another thing is to change model you gonna use for extraction, so in "extract_features_fp.py" find this line: 

`model = resnet50_baseline(pretrained=True)`

and replace it with (don't forget to import it first): 
`model = HIPT_4K()`

While already doing patching (create_patches_fp.py) don't forget to specify step size (I think it wasn't explicitly mentioned anywhere) since default one is 256 and you probably need 4096. 

Another hint: there are some slides with different patching level, we expect to have them at 40x (and set --patch_level to 1) yet some of them have 20x - you can remedy this problem by adding simple check to your code: 

```
import openslide
wsi_img = openslide.open_slide(full_path)
prop = wsi.properties
try:
    obj_power = prop['openslide.objective-power']
catch: 
    obj_power = '40'
    print('couldn't detect obj power, keeping default')

if obj_power  == '20':
    patch_level = 0
    print('patch lvl reverted to 0, 20x detected')
```

you probably can make the same trick with WSI_object (but I didn't check it)  in "crate_patches_fp.py" or just add above code in a right place. 

Another hint: while using "extract_patches_fp.py" specify --batch_size to 1

If you have any more questions or something is still unclear - let me know ;) I also struggled with setting it all for a while

**Comment by ShiCrazy** [comment]
@pniedziela Thanks for your patient and detailed reply! You are so nice and I am sure it will help those who want to use the HIPT but lack good programming skills like me. I didn't see your response in time yesterday and extracted features accidentally using an approach almost identical to yours, except for the first step. I got a feature with a shape of **torch.Size([1, 192])** without editing the codes about **features_cls256**&**features_cls4k**. I noticed the dicussion between you and @Rainydu184 and I am curious about the consequences of not editing the codes. Is this because the features with a shape of [1,192] cannot be trained, while the features with a shape of [1,256,384] can be trained using **main.py** of **CLAM** sacffold?

I'm not quite clear about your first hint. I've observed that some pathological images (Class A) have a magnification of 40x when **--patch_level** is set to 0, and 10x when **--patch_level** is set to 1. On the other hand, some other pathological images (Class B) have a magnification of 20x with --patch_level set to 0 and 5x with --patch_level set to 1. However, I haven't encountered any pathological images where the magnification is 40x at --patch_level 0 and 20x at --patch_level 1.
Before using HIPT, my approach was to segment patches from all pathological images at their default maximum magnification. However, the patch_size and step_size for Class A are twice that of Class B (like 512 and 256), and then I would handle them with different **custom_downsample** settings in "extract_features_fp.py". I'm guessing what you meant is to set the patch_level for Class A images to 1 and for Class B images to 0 during the "create_patches_fp" step. Wouldn't this result in inconsistent actual magnifications between the two classes?

Thank you again for helping me out of this struggle^_^

**Comment by pniedziela** [comment]
@ShiCrazy do you use your own dataset? Or TCGA? My point was that not all slides from TCGA comes with the same magnification at level 0, which might cause some troubles later (here we want to extract patches at 20x). Most of the time slides are 40X at the level 0 and 20X at level 1 so patch_level = 1 is the way to go - yet for some exceptions I used code like above to find them based on slide properties (some people use pixels to measure it etc.) and adjust case-specific patch_level. 
At least that's what I observed for LUSC/LUAD subtyping. 

And yes, you are right - it would be inconsistent to extract on different magnifications for various classes.

**Comment by ShiCrazy** [comment]
I did use my own dataset, but I also verified this situation on TCGA_BLCA. Below are the specifics of a pathological image at a maximum magnification of 40x, along with another pathological image at a maximum magnification of 20x.

> Opening Slide #877: /CUP_SVS/Shigb_CLAM_FGFR/clam_ostu_fgfr/slides/TCGA_BLCA/power40/TCGA-CU-A3YL-01Z-00-DX1.813C9F59-869C-4B8E-B295-22F67AD83F37.svs
/CUP_SVS/Shigb_CLAM_FGFR/clam_ostu_fgfr/slides/TCGA_BLCA/power40/TCGA-CU-A3YL-01Z-00-DX1.813C9F59-869C-4B8E-B295-22F67AD83F37.svs
Level count: 4
Level dimensions: ((171359, 73678), (42839, 18419), (10709, 4604), (2677, 1151))
Level downsamples: (1.0, 4.000089306586881, 16.002220762532453, 64.01187173161861)
Dimensions: (171359, 73678)
Objective power: 40
Associated images:
  thumbnail: <PIL.Image.Image image mode=RGBA size=1024x440 at 0x7F040F9048E0>
Format: aperio

> Opening Slide #2: /CUP_SVS/Shigb_CLAM_FGFR/clam_ostu_fgfr/slides/TCGA_BLCA/power20/TCGA-GC-A3OO-01A-01-TS1.95DFF291-07A6-4740-BE5F-78E7A1AD40E2.svs
/CUP_SVS/Shigb_CLAM_FGFR/clam_ostu_fgfr/slides/TCGA_BLCA/power20/TCGA-GC-A3OO-01A-01-TS1.95DFF291-07A6-4740-BE5F-78E7A1AD40E2.svs
Level count: 3
Level dimensions: ((15935, 16308), (3983, 4077), (1991, 2038))
Level downsamples: (1.0, 4.000376600552348, 8.00273926486658)
Dimensions: (15935, 16308)
Objective power: 20
Associated images:
  thumbnail: <PIL.Image.Image image mode=RGBA size=750x768 at 0x7F9B82B880A0>
Format: aperio

You can observe their Level dimensions and Level downsamples. The values of level_downsample[0] and level_downsample[1] are generally 1 and ~4, respectively. So far, I have not come across a situation where level_downsample[0] is 1 and level_downsample[1] is 2. Below is part of the code which can help to get slide information.

```
slide = openslide.open_slide(slide_filepath)
print("Level count: %d" % slide.level_count)
print("Level dimensions: " + str(slide.level_dimensions))
print("Level downsamples: " + str(slide.level_downsamples))
print("Dimensions: " + str(slide.dimensions))
objective_power = int(slide.properties[openslide.PROPERTY_NAME_OBJECTIVE_POWER])
print("Objective power: " + str(objective_power))
```

I'm not sure if the situation is the same for TCGA-LUSC/LUAD. You may want to re-examine this if necessary?

**Comment by XinyangHan** [comment]
Hey~ I patchify the WSI from TVCG-BRCA dataset using CLAM's create_patch.py and use the VIT-256 to extract its feature but faced the this error. May I ask your suggestions to solve that?
![image](https://github.com/mahmoodlab/HIPT/assets/86959032/e6fcd6c8-5d03-4a6c-b48b-36c21df0c181)
