### ISSUE TITLE
The results of each inference are inconsistent

### ISSUE THREAD

**Issue by yuzhuogu** [mahmoodlab/HIPT#59]
When creating heatmaps using create_hierarchical_heatmaps_indiv, the results are different each time and cannot be reproduced in the attention demo.

I have added mode.eval()

**Comment by v1t0ry** [comment]
I faced the same problem. The reason is that the ".pth" files in the Checkpoints folder are just pointers. And thus the model was initialized with random weights instead of pretrained weights.

To solve this problem, you have to download the ".pth" files directly, and make sure you provide the correct path to those ".pth" files when creating the model. A correct model initialization will output the following:

> Take key teacher in provided checkpoint dict
> Pretrained weights found at /path/to/.pth

**Comment by Richarizardd** [comment]
Thank you @v1t0ry. @yuzhuogu - please see [this thread ](https://github.com/mahmoodlab/HIPT/issues/56) which may be helpful.
